# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B -DskipTests clean package
    - name: Build Api Image
      run: docker build . -f docker/Dockerfile -t jimoos/jimoos-shop-api:$(date +%s)
    - name: Publish api to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jimoos/jimoos-shop-api
        dockerfile: docker/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Portal Image
      run: docker build . -f docker/portal-Dockerfile -t jimoos/jimoos-portal-api:$(date +%s)
    - name: Publish portal to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jimoos/jimoos-portal-api
        dockerfile: docker/portal-Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Migration Image
      run: docker build . -f docker/migration-Dockerfile -t jimoos/jimoos-shop-migration:$(date +%s)
    - name: Publish migration to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jimoos/jimoos-shop-migration
        dockerfile: docker/migration-Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
